name: Heldesk Issue
description: Used as output from helpdesk issue triage.
title: "[HD]: "
labels: ["helpdesk"]
assignees:
  - jadudm
body:
  - type: markdown
    attributes:
      value: |
        Lets make the FAC better by fixing all the things.
  - type: input
    id: zendesk-link
    attributes:
      label: Zendesk link
      description: Link to the issue in Zendesk
      placeholder: ex. https://fac-something.zendesk.com/something/...
    validations:
      required: false
  - type: checkboxes
    id: fac-components
    attributes:
      label: FAC components involved
      description: Select all that apply
      options:
        - label: submission system (app.fac.gov)
        - label: workbooks
        - label: static site (fac.gov)
        - label: The helpdesk (zendesk)
        - label: API (api.fac.gov)
        - label: other
    required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Paste the user's ticket here or otherwise summarize.
      placeholder: Please attach any workbooks/files included here by drag-and-dropping them onto the textarea.
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser did the user report as using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - None reported
        - Other (Opera, Brave, etc.)
